### ISSUE TITLE
Localização dos arquivos

### ISSUE THREAD

**Issue by AlexandroLuis** [E2PC/ProjectPage#21]
Seria o ideal seguir algo onde as pastas "E2PC e TL&PC" sejam as "mães", e dentro delas inserir as sub pastas de  cada projeto. Segue o exemplo a seguir:

Project/
├─ E2PC/
│  ├─section_1/
│  │ ├─section_1.md
│  │ ├─lorem.md
│  │ ├─ ipsum.md
├─ TL&PC/
│  ├─section_2/
│  │ ├─ section_2.md
│  │ ├─ dolor_sit.md
│  │ ├─ lorem.md
│  ├─section_3/
│  │ ├─ section_3.md
│  │ ├─ dolor_sit.md
│  │ ├─ lorem.md

😺

**Comment by Utzig26** [comment]
Concordo, farei as alterações e faço o link da issue no PR. :+1:

**Comment by AlexandroLuis** [comment]
Project/
├─section_1/
│ ├─section_1.md
│ ├─lorem.md
│ ├─ ipsum.md
│ ├─ images
│ ├─ archieves
├─section_2/
│ ├─ section_2.md
│ ├─ dolor_sit.md
│ ├─ lorem.md
│ ├─ images
