### ISSUE TITLE
Branch sem Utilização?

### ISSUE THREAD

**Issue by AlexandroLuis** [E2PC/ProjectPage#22]
O branch "add-cname" por exemplo, é realmente necessário? fiz a inserção do CNAME no gh-pages por padrão do github, existem milhares de branches, todos estão realmente fazendo sua função no desenvolvimento?

**Comment by Utzig26** [comment]
Por convenção sim. Facilita a organização do projeto e segue os padrões de revisão de código. No entanto, a branch poderia ser excluída logo em seguida.
Na maioria dos casos a branch deve ser excluída após o merge no master. Qualquer um pode fazê-lo, mas é comum que quem aceitou o PR faça-o logo aṕos.
O github libera o botão para deletar a branch logo na sequência do merge das branches.

>  ![image](https://user-images.githubusercontent.com/26260636/145615258-a90a3a76-bfcc-4a25-8e29-75fbced6ce1e.png)
