### ISSUE TITLE
Não utilizar links no titulo da página 

### ISSUE THREAD

**Issue by AlexandroLuis** [E2PC/ProjectPage#39]
Olá, acho que seria melhor considerar não utilizar links no título de páginas, mas sim os colocando nas mesmas palavras chave em alguma parte relevante do texto, como no exemplo a seguir:
![fgfdgfdg](https://user-images.githubusercontent.com/52381045/163894129-58648e04-7108-400a-b4cf-51c3997cd422.png)
, Acho que seria interessante remover por questões de estética o link como título dessa página, o que acham?

**Comment by EricPatrickM** [comment]
problema resolvido
