### ISSUE TITLE
Organizar tópicos na aba "Treinamento"

### ISSUE THREAD

**Issue by aetpiekarski** [E2PC/ProjectPage#47]
Os tópicos estão em ordem alfabética, mas é melhor que fiquem em uma sequência didática.
A ordem deve ser: 
[Leitura e escrita de dados](https://e2pc.unicentro.br/treinamento/leitura_escrita.html)
  Renomear esse item para "Como resolver um problema - Primeiros passos" 
[Entrada e saída](https://e2pc.unicentro.br/treinamento/entrada_saida.html)
[Formatação de casas decimais] (está na aba Programação competitiva) 
[Estrutura de seleção](https://e2pc.unicentro.br/treinamento/estruturas_selecao.html)
[Operadores lógicos](https://e2pc.unicentro.br/treinamento/operadores_logicos.html)
[Estrutura de repetição](https://e2pc.unicentro.br/treinamento/estruturas_repeticao.html)
[Vetores](https://e2pc.unicentro.br/treinamento/vetores.html)

Mover para a aba Programação competitiva, antes de "Comparar arquivos": [Redirecionamento de entrada](https://e2pc.unicentro.br/treinamento/redirecionamento_entrada.html)

**Comment by danielmbrasil** [comment]
@aetpiekarski o item que deve ser renomeado para "Como resolver um problema - Primeiros passos" é o de "Leitura e escrita de dados" ou "Entrada e saída"?
