### ISSUE TITLE
Inserir cards na aba Equipe

### ISSUE THREAD

**Issue by aetpiekarski** [E2PC/ProjectPage#51]
Em cada card conterá:
- nome do participante
- link do LinkedIn
- link do Lattes
- foto?
- e-mail?

**Comment by AlexandroLuis** [comment]
Acredito que foto não seria muito interessante, e utilizar o link de perfis como botões contendo a imagem do que é o link semelhante a esse exemplo:
![sdfsdfdsf](https://user-images.githubusercontent.com/52381045/166127072-e286226a-b34e-4842-818c-96db9a22af52.png)
Você clica nos botões e vai para o perfil correspondente
