### ISSUE TITLE
Substituir logo do projeto

### ISSUE THREAD

**Issue by aetpiekarski** [E2PC/ProjectPage#68]
Alterar a página de estilo, substituindo o logo do projeto.

**Comment by aetpiekarski** [comment]
Solicitei o favicon, via OS, mas ainda não tive resposta.

**Comment by aetpiekarski** [comment]
![LOGO E2PC APROVADO](https://user-images.githubusercontent.com/90481393/171740352-5bfb971a-d704-48ff-8952-cc43ce0df121.svg)

**Comment by AlexandroLuis** [comment]
O logo do projeto foi alterado na pull request https://github.com/E2PC/ProjectPage/pull/71
