### ISSUE TITLE
Ver padrão de redimensionamento de tela 

### ISSUE THREAD

**Issue by aetpiekarski** [E2PC/ProjectPage#69]
As abas de conteúdo de "Treinamento" não estão adequando o conteúdo ao tamanho da janela.
Percebi quando abri no celular, e qdo redimensiona no PC tb acontece:
![image](https://user-images.githubusercontent.com/90481393/171003905-136f8639-6904-47c1-a9ef-c779fd406ea7.png)
Veja a diferença das duas telas...

**Comment by aetpiekarski** [comment]
Ah, sim, e no celular não é possível deslocar, fica travado com o conteúdo do centro da tela...

**Comment by AlexandroLuis** [comment]
Olá, realizei testes e analisei as questões sobre a responsividade das páginas do projeto e acredito que tenha sido apenas um bug. Realizando os restes as páginas se comportam de forma adequada, seguindo os exemplos abaixo:

Dispositivo Mobile:
![WhatsApp Image 2022-06-01 at 5 06 45 PM](https://user-images.githubusercontent.com/52381045/171492974-d666c8be-b7d2-4834-89fb-a83550d95cee.jpeg)

Redimensionando a tela utilizando o Google Chome:
![retertert](https://user-images.githubusercontent.com/52381045/171493297-90e6c3cb-9c8a-4ee1-aff3-533080f0c04e.png)


Redimensionando a tela inspecionando a página e visualizando por dispositivos:
![dsfdsafsdf](https://user-images.githubusercontent.com/52381045/171493169-a4cd6952-e7d8-4cf4-99e2-1d53cb373ed8.png)

Esse problema ocorreu apenas quando a resolução da tela foi inferior a 645x657. O problema pode ser o layout da página que está dando algum conflito dentro das páginas do "Treinamento", vou dar uma olhada na questão da estrutura em que essas páginas foram construídas(o seu conteúdo).

**Comment by AlexandroLuis** [comment]
Esse problema foi resolvido na pull request https://github.com/E2PC/ProjectPage/pull/71
